[app]
title = Twishu
package.name = twishu
package.domain = org.twishu
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 1.0

requirements = python3,kivy,kivymd,plyer,speechrecognition,groq,requests

android.permissions = INTERNET,RECORD_AUDIO,READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE

orientation = portrait

android.api = 33
android.minapi = 21
android.build_tools = 34.0.0
android.accept_sdk_license = True     # ← Yeh line sabse important hai

android.archs = arm64-v8a, armeabi-v7a
fullscreen = 0
android.allow_backup = True

[buildozer]
log_level = 2
warn_on_root = 1
