name: Build Twishu APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip git zip unzip openjdk-17-jdk pkg-config \
            libgl1-mesa-dev libgles2-mesa-dev libgstreamer1.0-0 libgstreamer-plugins-base1.0-0 \
            libsm6 libxext6 libxrender1 libx11-dev libssl-dev

      - name: Install Buildozer + Cython
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer cython==3.0.11

      - name: Accept Android Licenses
        run: |
          echo "y" | sdkmanager --licenses || true
          yes | sdkmanager --licenses || true

      - name: Build APK
        run: |
          buildozer -v android debug
        working-directory: ./

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Twishu-APK
          path: bin/*.apk
